# -*- coding: utf-8 -*-
"""Copy of Pestornot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13ylyAA0ZrJZnKfJpeXzAP2ArzyM1abZN
"""

import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
from sklearn.metrics import confusion_matrix, classification_report, roc_curve, auc

import tensorflow as tf
from tensorflow.keras import layers, models
from google.colab import drive, files

# --- 1. MOUNT GOOGLE DRIVE ---
drive.mount('/content/drive')

# --- 2. SETTINGS ---
IMG_SIZE = (224, 224)
BATCH_SIZE = 32
# Based on your Drive structure:
DATA_DIR = '/content/drive/MyDrive/PestOrNot'

# --- 3. LOAD DATA ---
# This will automatically pick up "Pest" and "Not_Pest" folders
train_ds = tf.keras.utils.image_dataset_from_directory(
    DATA_DIR,
    validation_split=0.2,
    subset="training",
    seed=123,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    DATA_DIR,
    validation_split=0.2,
    subset="validation",
    seed=123,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

class_names = train_ds.class_names # Expected: ['Not_Pest', 'Pest']
print(f"Detected classes: {class_names}")

# --- 4. MODEL BUILDING ---
base_model = tf.keras.applications.MobileNetV2(
    input_shape=(224, 224, 3),
    include_top=False,
    weights='imagenet'
)
base_model.trainable = False

model = models.Sequential([
    layers.Rescaling(1./255, input_shape=(224, 224, 3)),
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# --- 5. TRAINING ---
print("\nStarting Training...")
history = model.fit(train_ds, validation_data=val_ds, epochs=10)

# --- 6. EVALUATION ---
y_true = []
y_pred_probs = []

# Iterate through validation set to get all labels and predictions
for images, labels in val_ds:
    y_true.extend(labels.numpy())
    preds = model.predict(images, verbose=0)
    y_pred_probs.extend(preds.flatten())

y_true = np.array(y_true)
y_pred_probs = np.array(y_pred_probs)
y_pred = (y_pred_probs > 0.5).astype(int)

# Classification Metrics
print("\n--- Detailed Metrics ---")
print(classification_report(y_true, y_pred, target_names=class_names))

# Confusion Matrix
plt.figure(figsize=(8, 6))
cm = confusion_matrix(y_true, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Greens',
            xticklabels=class_names, yticklabels=class_names)
plt.title('Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

# ROC-AUC Plot
fpr, tpr, _ = roc_curve(y_true, y_pred_probs)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color='forestgreen', lw=2, label=f'ROC curve (AUC = {roc_auc:.2f})')
plt.plot([0, 1], [0, 1], color='gray', linestyle='--')
plt.title('Receiver Operating Characteristic (ROC)')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.legend(loc="lower right")
plt.grid(alpha=0.3)
plt.show()

# --- 7. VISUALIZE PREDICTIONS ---
plt.figure(figsize=(12, 12))
for images, labels in val_ds.take(1):
    preds = model.predict(images, verbose=0)
    for i in range(9):
        plt.subplot(3, 3, i + 1)
        # Convert back to uint8 for display since we rescaled in the model
        plt.imshow(images[i].numpy().astype("uint8"))

        prob = preds[i][0]
        # Logic for Pest/Not Pest
        label_str = "Pest" if prob > 0.5 else "Not Pest"
        confidence = prob if prob > 0.5 else 1 - prob

        # Color code: Green if correct, Red if wrong
        true_label_str = class_names[labels[i]]
        color = 'green' if label_str == true_label_str else 'red'

        plt.title(f"Pred: {label_str} ({confidence:.1%})\nActual: {true_label_str}", color=color)
        plt.axis("off")
plt.tight_layout()
plt.show()

# --- 8. SAVE & DOWNLOAD .PKL ---
# Saving the weights and architecture to a pickle file
model_data = {
    'weights': model.get_weights(),
    'config': model.get_config(),
    'classes': class_names
}

with open('pest_detector_model.pkl', 'wb') as f:
    pickle.dump(model_data, f)

print("\nDownloading the .pkl file...")
files.download('pest_detector_model.pkl')